import React from 'react'

export const About = () => {

    return (
        <div className="container my-5">
            <h2>About Application Aryan Official</h2>
            {/* <p>This company, 'Application Aryan Official' was created by Mr. Aryan Sisodiya, our founder. The story starts when he was just 13 years old and a 8th class Student, the one of his interest was Programming, at that time his teacher was teaching him Python, one of the chapter of his computer book. When he started Python Programming His aim was to complete Python, to learn it completely and he did, He completed his Python Programming in about 4 months, He then wanted to create apps that excute with a Graphical Window not in a boring console, that was the point when he started programming for GUI's, he started learning Tkinter from the free of cost YouTube Channel 'CodeWithHarry', as soon as he completed Tkinter. In about 2 months and started creating Python Apps. The name 'Application Aryan Official' came to mind of Mr. Aryan Sisodiya when he was the making the first application of his first Programming Language, Python. He want to give a greeting message to his users who will use his Applications but he was not having any Frictional Company name, then he thought about the 'Khan Sir', one of the Teacher from Bihar and having a YouTube Channel, he was liked to see his videos, At that time, Khan Sir launched his Application 'Khan Sir Official'. So the name 'Application Aryan Official' came into his mind and named his Frictional Company. As soon as he completed complete Web Development and started creating Websites and he converted the Frictional Company 'Application Aryan Official' into a real Company.</p> */}
            <p>
                Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quia, mollitia est sunt error quos reiciendis recusandae, dolores eaque repudiandae reprehenderit alias animi perferendis velit similique dolore, quas sit laborum numquam obcaecati rerum delectus. Maxime assumenda nobis ipsam voluptas? Placeat autem rerum enim fugiat animi, perspiciatis porro nihil repellat eligendi eos, at non adipisci amet, pariatur distinctio dolores labore perferendis. Omnis minima ut impedit magni, excepturi similique a. Reprehenderit dignissimos provident fugiat, ex pariatur, dolore totam in obcaecati odio dolorem quos ullam ipsum rerum placeat, quo autem explicabo optio? Id veritatis corporis voluptatibus reprehenderit debitis iste? Reprehenderit eveniet tenetur ab animi sint dolorum deleniti eos assumenda numquam ipsa at praesentium cum in placeat illo recusandae vel, ex fugit eligendi soluta facere, omnis eius officia accusamus. Deleniti, enim molestias laudantium corrupti quis dignissimos magni facere, alias ex ea earum porro natus placeat, vel quisquam necessitatibus? Quidem placeat assumenda, distinctio voluptas repellendus, ipsam dolorum, omnis cum praesentium fuga illum a enim magni. Iure odio dolores incidunt reiciendis, nihil quae iste cupiditate aliquam dignissimos quibusdam quam, assumenda quia doloremque magnam sit repudiandae ab sequi eius expedita at ipsa deleniti tempore totam? Ullam veritatis praesentium magnam, inventore laudantium magni consequatur molestiae explicabo similique modi. Eligendi officiis placeat illo facere quae dolorem magnam, libero blanditiis eveniet aliquam earum culpa perspiciatis pariatur sint recusandae quam optio, illum vero vitae id facilis qui et. Obcaecati quasi reiciendis distinctio sapiente consequuntur laboriosam ipsam repellat iusto quam. Ullam facilis, quas incidunt inventore, unde expedita laboriosam itaque assumenda harum, nihil ducimus beatae? Recusandae odit dicta repellat a voluptatum. Ad, quibusdam tempora.
            </p>
            <h1 className="text-center">
                We hope you might Like!
            </h1>
        </div>
    )
}
